project_id = "nzkmirpfupvwdxqgixtz"

[functions.ocr-api]
verify_jwt = false

[functions.ocr-document]
verify_jwt = false

[functions.ocr-id-card]
verify_jwt = false

[functions.ocr-id-card-api]
verify_jwt = false